Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -26,6 +26,16 @@ jobs:
       
     - name: Xcode version
       run: /usr/bin/xcodebuild -version
+
+   
       
     - name: Build and Test
-      run: xcodebuild clean build test -project WorldOfPAYBACK.xcodeproj -scheme "CI_iOS" -testPlan "CI_iOS" -only-test-configuration "English" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13" ONLY_ACTIVE_ARCH=YES
+      run: xcodebuild clean build test -project WorldOfPAYBACK.xcodeproj -scheme "CI_iOS" -resultBundlePath TestResults -testPlan "CI_iOS" -only-test-configuration "English" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13" ONLY_ACTIVE_ARCH=YES
+
+    - uses: kishikawakatsumi/xcresulttool@v1
+      with:
+        path: TestResults.xcresult
+        if: success() || failure()
+        # ^ This is important because the action will be run
+        # even if the test fails in the previous step.
+    
